import {dayResultsApi} from "@/services/dayResultsService.ts";

const goalsApiSlice = dayResultsApi.injectEndpoints({
    endpoints: (builder) => ({
        getGoalsHeadersByUserId: builder.query({
            query: (userId) => ({
                url: `/goals/getAllGoalsHeaders/${userId}`,
                method: "GET",
            }),
            providesTags: (result) =>
                ["goalsHeaders"]
        }),
        addGoal: builder.mutation({
            query: ({userId, title}) => ({
                url: `/goals/addGoal/${userId}`,
                method: "PUT",
                body: {
                    title
                },
            }),
            invalidatesTags: ["goalsHeaders", "dayResults"],
        }),
        deleteGoal: builder.mutation({
            query: (goalId) => ({
                url: `/goals/deleteGoal/${goalId}`,
                method: "DELETE",
            }),
            invalidatesTags: ["goalsHeaders", "dayResults"],
        }),
    }),
});

// Export hooks generated by RTK Query for use in components
export const {
    useGetGoalsHeadersByUserIdQuery,
    useAddGoalMutation,
    useDeleteGoalMutation,
} = goalsApiSlice;